### ISSUE TITLE
Error when I try to run on my Windows 10 PC

### ISSUE THREAD

**Issue by byomartin** [vogelcodes/capcut-srt-export#3]
`C:\Users\admin\Desktop\capcut-srt-export-main>node index.js
C:\Users\admin\Desktop\capcut-srt-export-main\index.js:30
  if (re.exec(i.content)[1].substring(0,1) === '<') {
                        ^

TypeError: Cannot read properties of null (reading '1')
    at ←[90mC:\Users\admin\Desktop\capcut-srt-export-main\←[39mindex.js:30:25
    at Array.map (<anonymous>)
    at Object.<anonymous> ←[90m(C:\Users\admin\Desktop\capcut-srt-export-main\←[39mindex.js:28:37←[90m)←[39m
←[90m    at Module._compile (node:internal/modules/cjs/loader:1159:14)←[39m
←[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:1037:32)←[39m
←[90m    at Module._load (node:internal/modules/cjs/loader:878:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)←[39m
←[90m    at node:internal/main/run_main_module:23:47←[39m

Node.js v18.12.1`

It's ridiculous because I run it 3 times before without problem.

**Comment by vogelcodes** [comment]
Can you send me your draft_content.json to danielcvt@gmail.com?

**Comment by byomartin** [comment]
> Can you send me your draft_content.json to [danielcvt@gmail.com](mailto:danielcvt@gmail.com)?

it's here https://pastebin.com/raw/aC0y6ekW

thank you for quick reply.

**Comment by vogelcodes** [comment]
Hi. It seems your project file had mixed syntax for the subtitles content which caused a bug. I wrote a quick fix that solved the issue. Download the script again from github.
