### ISSUE TITLE
WebUI Not Available

### ISSUE THREAD

**Issue by MrPanda-to-you** [vogelcodes/capcut-srt-export#4]
Hi!
The WebUI (https://capcut-srt-export.vogelcodes.com/) is not available anymore?
Thank you!

**Comment by vogelcodes** [comment]
I had a small issue with the stats database. But it's working now.

Em sáb., 7 de jan. de 2023 às 10:43, MrPanda-to-you <
***@***.***> escreveu:

**Comment by MrPanda-to-you** [comment]
You are awesome! Thanks man...
